[  {ticker:"null", name :"INPUT TAX CREDIT  "},
  {ticker:"null", name :"INPUT TAX CREDIT UNDER GST  "},
  {ticker:"null", name :"GST REGISTRATION  "},
  {ticker:"null", name :"GST REGISTRATION CERTIFICATE  "},
  {ticker:"null", name :"GST RETURN "},
  {ticker:"null", name :"GST RETURN "},
  {ticker:"null", name :"GSTR-3B "},
  {ticker:"null", name :"GSTR-1 "},
  {ticker:"null", name :"ANNUAL RETURN GSTR 9 "},
  {ticker:"null", name :"PLACE OF SUPPLY IN GST "},
  {ticker:"null", name :"TIME OF SUPPLY IN GST "},
  {ticker:"null", name :"VALUATION OF SUPPLY UNDER GST "},
  {ticker:"null", name :"EWAY BILL UNDER GST "},
  {ticker:"null", name :"E INVOICING UNDER GST "},
  {ticker:"null", name :"COMPOSITION SCHEME UNDER GST "},
  {ticker:"null", name :"CHARGE OF GST  "},
  {ticker:"null", name :"EXEMPTION FROM GST "},
  {ticker:"null", name :"TAX INVOICE UNDER GST "},
  {ticker:"null", name :"CREDIT NOTE AND DEBIT NOTE IN GST "},
  {ticker:"null", name :"JOB WORK UNDER GST "},
  {ticker:"null", name :"REVERSE CHARGE UNDER GST "},
  {ticker:"null", name :"TDS UNDER GST "},
  {ticker:"null", name :"TCS UNDER GST "},
  {ticker:"null", name :"REFUND UNDER GST "},
  {ticker:"null", name :"SHOW CAUSE NOTICE UNDER GST "},
  {ticker:"null", name :"SCN UNDER GST "},
  {ticker:"null", name :"NOTICE UNDER GST "},
  {ticker:"null", name :"SUMMONS UNDER GST "},
  {ticker:"null", name :"PROSECUTION UNDER GST "},
  {ticker:"null", name :"SEARCH UNDER GST "},
  {ticker:"null", name :"OFFENCES AND PENALTIES UNDER GST"},
]

  {
        name: "Reliance Industries Ltd.",
        ticker: "RELIANCE",
      },